# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

executors:
  android-executor:
    docker:
      - image: circleci/android:api-29
    working_directory: ~/aam
    environment:
      JAVA_TOOL_OPTIONS: "-Xmx2048m"
      GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2"
      TERM: dumb

jobs:
  build:
    executor: android-executor
    steps:
      - checkout
      - run:
          name: Download Dependencies
          command: ./gradlew dependencies
      - run:
          name: Check
          command: ./gradlew check --stacktrace
  check_apk_size_change:
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout
      - run:
          name: Check Apk Size
          command: sh ./scripts/check_apk_size.sh

workflows:
  verify:
    jobs:
      - check_apk_size_change