# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

executors:
  android_executor:
    docker:
      - image: circleci/android:api-29
    working_directory: ~/aam
    environment:
      JAVA_TOOL_OPTIONS: "-Xmx2048m"
      GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2"
      TERM: dumb

jobs:
  build-release-apk:
    executor: android_executor
    steps:
      - checkout
      - run:
          name: Build Release Apk
          command: sh ./scripts/build_release_apk.sh
      - store_artifacts:
          path: ./build/universal.apk
      - persist_to_workspace:
          root: .
          paths:
            - build
            - ./**/build
  compare_apk:
    docker:
      - image: google/cloud-sdk
    steps:
      - run:
          name: Compare apk
          command: sh ./scripts/compare_apk.sh

workflows:
  version: 2
  pull-request-flow:
    jobs:
      - build-release-apk:
          filters:
            branches:
              ignore:
                - master
      - compare_apk:
          requires:
            - build_release_apk